pipeline {
    agent ( dockerfile true }

    stages {
        stage('Build') {
            agent {
                sh 'terraform --version'
            }
            steps {
                echo 'Running terraform init'
                sh 'conftest --version'
            }
        }
        stage('Test') {
            steps {
                echo 'Running terraform plan'
                //sh 'terraform plan'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Running terraform apply'
              //  sh 'terraform apply -auto-approve'
            }
        }
    }
}
