pipeline {
    agent none

    stages {
        stage('Build') {
            agent {
                docker {image 'openpolicyagent/opa'}
            }
            steps {
                echo 'Running terraform init'
                sh 'terraform init'
            }
        }
        stage('Test') {
            steps {
                echo 'Running terraform plan'
                sh 'terraform plan'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Running terraform apply'
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
